version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationski
    volumes:
      - db_vol:/var/lib/mysqldb

  instructor_app:
    build: .
    image: nourbououn-5sae5-g1
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

volumes:
  db_vol: